%bcond_without tests

%global commit 267a171c9570b4a1f819879a4c881862a25188eb
%global shortcommit 267a171
%global snapshot 20260904
%global source_manifest_sha256 54a976e8240457856d420d5035a35f55aef948462850c9c604ad167166ddc63b
%global openssl_fork_evr 1:4.1.0~dev.1-0.4.git9bbfc53%{?dist}
%global provider_modulesdir %{_libdir}/ossl-modules
%global __provides_exclude_from ^%{provider_modulesdir}/.*\.so$

Name:           g301-openssl-provider
Version:        0.1.0
Release:        0.6.%{snapshot}git%{shortcommit}%{?dist}
Summary:        Experimental G301 TLS record provider for OpenSSL
License:        Apache-2.0
URL:            https://github.com/ychromosome/g301-openssl-provider
# GitHub does not publish subtree archives. Source0 is generated by Source2 so
# that the separately licensed inner-threads/ subtree never enters the SRPM.
Source0:        g301-openssl-provider-%{commit}.tar.gz
Source1:        g301-provider.conf
Source2:        generate-g301-source.sh
Source3:        opensslcnf-zz-g301.config
Source4:        README.g301-policy

BuildRequires:  cmake
BuildRequires:  gcc
BuildRequires:  binutils
BuildRequires:  openssl-devel = %{openssl_fork_evr}
%if %{with tests}
BuildRequires:  openssl = %{openssl_fork_evr}
BuildRequires:  pkgconfig(mbedcrypto)
BuildRequires:  python3
%endif

Requires:       openssl-libs%{?_isa} = %{openssl_fork_evr}

%description
G301-AES-256-GCM-V1 is an experimental TLS 1.3 record provider. It delegates
AES-256-GCM to OpenSSL and advertises private-use cipher suite 0xff30. The
package activates the provider but does not change Fedora's TLS cipher-suite
or group preference. G301 is not standardized or FIPS validated.

%package policy
Summary:        G301 OpenSSL policy-fragment example
BuildArch:      noarch
Requires:       %{name} = %{version}-%{release}
# Rebuild once after upgrading from releases that installed a local.d file.
Requires(posttrans): crypto-policies-scripts

%description policy
This laboratory package contains an inert OpenSSL policy-fragment example.
It does not change the selected Fedora crypto policy.

%prep
%autosetup -n g301-openssl-provider-%{commit}/outer-tls
test "$(sha256sum SOURCE_MANIFEST.sha256 | awk '{ print $1 }')" = \
    %{source_manifest_sha256}
sha256sum --strict --quiet -c SOURCE_MANIFEST.sha256
install -pm 0644 %{SOURCE4} README.g301-policy
install -pm 0644 %{SOURCE3} opensslcnf-zz-g301.config.example

%build
%if %{with tests}
%cmake \
    -DBUILD_TESTING:BOOL=ON \
    -DG301_ENABLE_PRIVATE_TLS_E2E:BOOL=ON \
    -DG301_ENABLE_MBEDTLS_ORACLE:BOOL=ON
%else
%cmake \
    -DBUILD_TESTING:BOOL=OFF \
    -DG301_ENABLE_PRIVATE_TLS_E2E:BOOL=OFF \
    -DG301_ENABLE_MBEDTLS_ORACLE:BOOL=OFF
%endif
%cmake_build

%install
install -Dpm 0755 %{__cmake_builddir}/g301.so \
    %{buildroot}%{provider_modulesdir}/g301.so
install -Dpm 0644 %{SOURCE1} \
    %{buildroot}%{_sysconfdir}/pki/tls/openssl.d/g301-provider.conf

%check
%if %{with tests}
%ctest

module=%{buildroot}%{provider_modulesdir}/g301.so
test -f "$module"
test "$(nm -D --defined-only "$module" \
    | awk '$2 == "T" { count++ } END { print count + 0 }')" -eq 1
nm -D --defined-only "$module" | grep -E ' T OSSL_provider_init$' >/dev/null
if readelf -d "$module" | grep -Eq '\((RPATH|RUNPATH)\)'; then
    echo 'provider module contains an RPATH or RUNPATH' >&2
    exit 1
fi
readelf -lW "$module" | grep -E 'GNU_STACK.*RW ' >/dev/null

OPENSSL_CONF=/dev/null \
OPENSSL_MODULES=%{buildroot}%{provider_modulesdir} \
openssl list -provider-path %{buildroot}%{provider_modulesdir} \
    -provider default -provider g301 -cipher-algorithms \
    | grep -F G301-AES-256-GCM-V1 >/dev/null
%endif

%files
%license LICENSE LICENSE_SCOPE.md
%doc BUILDING.md README.md SECURITY.md THIRD_PARTY_NOTICES.md
%config(noreplace) %{_sysconfdir}/pki/tls/openssl.d/g301-provider.conf
%{provider_modulesdir}/g301.so

%posttrans
echo 'WARNING: G301-AES-256-GCM-V1 is experimental, private-use and not FIPS validated.'
echo 'The provider is active for newly started OpenSSL applications.'
echo 'Fedora TLS cipher-suite and group preferences were not changed.'
exit 0

%files policy
%doc README.g301-policy opensslcnf-zz-g301.config.example

%posttrans policy
if ! %{_bindir}/update-crypto-policies; then
    echo 'error: failed to remove a previous G301 policy overlay' >&2
    exit 1
fi
echo 'The G301 policy fragment is installed as inert documentation.'
exit 0

%changelog
* Fri Sep 04 2026 Martin Wolf <mwolf@adiumentum.com> - 0.1.0-0.6.20260904git267a171
- Define the record limit per uninterrupted write-key installation
- Ship the policy fragment as inert documentation
- Require the OpenSSL SNI-fix RPM

* Wed Sep 02 2026 Martin Wolf <mwolf@adiumentum.com> - 0.1.0-0.5.20260902git07da4c8
- Exclude local Python cache files from the source inventory

* Wed Sep 02 2026 Martin Wolf <mwolf@adiumentum.com> - 0.1.0-0.4.20260902git90b4082
- State the cipher-context record-budget boundary
- Locate versioned LLVM analyzer installations
- Pin the rebuilt OpenSSL review fork

* Tue Sep 01 2026 Martin Wolf <mwolf@adiumentum.com> - 0.1.0-0.3.20260901gitbd59af3
- Split the optional G301 cipher-suite preference into a policy subpackage

* Tue Sep 01 2026 Martin Wolf <mwolf@adiumentum.com> - 0.1.0-0.2.20260901gitbd59af3
- Prepend G301 while preserving the Fedora TLS cipher-suite fallback

* Tue Sep 01 2026 Martin Wolf <mwolf@adiumentum.com> - 0.1.0-0.1.20260901gitbd59af3
- Initial G301 outer-provider package
